// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Which connection the Prisma CLI should use.
 *
 * Checks the shape of DIRECT_DATABASE_URL before handing it over, because
 * Prisma's own complaint about a bad one is "P1013: The scheme is not
 * recognized in database URL", printed next to an empty datasource line. That
 * is technically accurate and tells you nothing about which variable is wrong
 * or what it should look like — and it costs a full deploy to find out.
 */
function migrationUrl(): string | undefined {
  const direct = process.env["DIRECT_DATABASE_URL"]?.trim();
  if (!direct) return process.env["DATABASE_URL"];

  if (!/^postgres(ql)?:\/\//.test(direct)) {
    throw new Error(
      `DIRECT_DATABASE_URL is set but is not a connection string — it starts with ` +
        `"${direct.slice(0, 24)}…".

` +
        `It needs the whole URL, not just the host. Take DATABASE_URL and delete ` +
        `"-pooler" from the hostname:

` +
        `  postgresql://user:password@ep-xxx.region.aws.neon.tech/neondb?sslmode=require

` +
        `Migrations need the direct endpoint because a connection pooler cannot ` +
        `hold the session-level advisory lock they take.`,
    );
  }
  return direct;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    /**
     * Migrations run on the direct connection, not the pooled one.
     *
     * Prisma Migrate takes a session-level advisory lock so two deploys can't
     * migrate at once. A connection pooler doesn't hold a session — each
     * statement may land on a different backend — so `pg_advisory_lock` never
     * resolves and the CLI dies with P1002 after ten seconds. That is exactly
     * how the first build-time migration failed against Neon's `-pooler`
     * endpoint.
     *
     * Only the CLI reads this file. The application takes DATABASE_URL straight
     * from the environment in lib/prisma.ts and keeps using the pooled
     * endpoint, which is the right one for serverless request traffic.
     */
    url: migrationUrl(),
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
