/**
 * Seed the database with a realistic-looking catalog so the site is browsable
 * before any live ingestion runs.
 *
 * The figures, manufacturers and series here are real products; the *prices* are
 * synthetic — generated by a seeded random walk so charts have something to draw.
 * Once the eBay/AmiAmi jobs run, real snapshots accumulate alongside these.
 *
 * Run with: npm run db:seed   (safe to re-run — everything upserts)
 */
import "dotenv/config";
import type { FigureCategory, ReleaseStatus } from "../lib/generated/prisma/enums";
import { prisma } from "../lib/prisma";
import { median, recomputeFigureStats } from "../lib/ingest/aggregate";
import { rebuildAllSearchText } from "../lib/ingest/search-index";
import { slugify } from "../lib/utils";

// --- Deterministic PRNG so re-seeding produces the same charts -------------
function makeRng(seed: number) {
  let s = seed >>> 0;
  return () => {
    // mulberry32
    s = (s + 0x6d2b79f5) >>> 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const MANUFACTURERS = [
  { name: "Good Smile Company", websiteUrl: "https://www.goodsmile.com" },
  { name: "Alter", websiteUrl: "https://www.alter-web.jp" },
  { name: "Kotobukiya", websiteUrl: "https://www.kotobukiya.co.jp" },
  { name: "Max Factory", websiteUrl: "https://maxfactory.jp" },
  { name: "Bandai Spirits", websiteUrl: "https://www.bandaispirits.co.jp" },
  { name: "FREEing", websiteUrl: "https://www.freeing.co.jp" },
  { name: "Ques Q", websiteUrl: null },
  { name: "Aniplex", websiteUrl: "https://www.aniplex.co.jp" },
];

const SERIES = [
  "Fate/Grand Order",
  "My Dress-Up Darling",
  "Oshi no Ko",
  "Spy x Family",
  "Frieren: Beyond Journey's End",
  "Chainsaw Man",
  "Re:Zero",
  "Demon Slayer",
  "Hatsune Miku",
  "Jujutsu Kaisen",
];

type SeedFigure = {
  name: string;
  series: string;
  character: string;
  manufacturer: string;
  category: FigureCategory;
  status?: ReleaseStatus;
  scale?: string;
  heightMm?: number;

  /**
   * Release date and MSRP are optional on purpose.
   *
   * Some figures were added from evidence in marketplace listings, where the
   * product is certain but its original retail price and release month are not.
   * Leaving them out shows "—" on the site; inventing them would be the
   * synthetic-price mistake wearing a different hat.
   */
  releaseYear?: number;
  releaseMonth?: number;
  msrpJpy?: number;

  /** JAN/EAN barcode, when known. The most reliable way to identify a figure. */
  jan?: string;

  // --- Only used by --demo-prices. Absent for anything added since. ---
  /** Roughly where the secondary market sits today, in USD. */
  marketUsd?: number;
  /** Long-run drift per year as a fraction. 0.4 = a grail climbing ~40%/yr. */
  drift?: number;
  /** Day-to-day noise. Prize figures are quiet; grails are volatile. */
  volatility?: number;
};

const FIGURES: SeedFigure[] = [
  {
    name: "Marin Kitagawa 1/7 Swimsuit Ver.",
    series: "My Dress-Up Darling",
    character: "Marin Kitagawa",
    manufacturer: "Good Smile Company",
    category: "SCALE",
    scale: "1/7",
    heightMm: 210,
    releaseYear: 2023,
    releaseMonth: 8,
    msrpJpy: 21800,
    marketUsd: 245,
    drift: 0.28,
    volatility: 0.021,
  },
  {
    name: "Nendoroid Marin Kitagawa",
    series: "My Dress-Up Darling",
    character: "Marin Kitagawa",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
    releaseYear: 2022,
    releaseMonth: 11,
    msrpJpy: 6500,
    marketUsd: 88,
    drift: 0.12,
    volatility: 0.014,
  },
  {
    name: "Ai Hoshino 1/7 Stage Ver.",
    series: "Oshi no Ko",
    character: "Ai Hoshino",
    manufacturer: "Alter",
    category: "SCALE",
    scale: "1/7",
    heightMm: 240,
    releaseYear: 2024,
    releaseMonth: 6,
    msrpJpy: 27500,
    marketUsd: 410,
    drift: 0.55,
    volatility: 0.031,
  },
  {
    name: "Nendoroid Ai Hoshino",
    series: "Oshi no Ko",
    character: "Ai Hoshino",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
    releaseYear: 2024,
    releaseMonth: 2,
    msrpJpy: 7200,
    marketUsd: 96,
    drift: 0.18,
    volatility: 0.016,
  },
  {
    name: "Anya Forger 1/7 Elegant Ver.",
    series: "Spy x Family",
    character: "Anya Forger",
    manufacturer: "Kotobukiya",
    category: "SCALE",
    scale: "1/7",
    heightMm: 165,
    releaseYear: 2023,
    releaseMonth: 12,
    msrpJpy: 19800,
    marketUsd: 178,
    drift: 0.09,
    volatility: 0.018,
  },
  {
    name: "Nendoroid Anya Forger",
    series: "Spy x Family",
    character: "Anya Forger",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
    releaseYear: 2023,
    releaseMonth: 5,
    msrpJpy: 6800,
    marketUsd: 72,
    drift: 0.05,
    volatility: 0.012,
  },
  {
    name: "Frieren 1/7 Scale Figure",
    series: "Frieren: Beyond Journey's End",
    character: "Frieren",
    manufacturer: "Good Smile Company",
    category: "SCALE",
    scale: "1/7",
    heightMm: 220,
    releaseYear: 2025,
    releaseMonth: 3,
    msrpJpy: 24800,
    marketUsd: 268,
    drift: 0.34,
    volatility: 0.026,
  },
  {
    name: "figma Frieren",
    series: "Frieren: Beyond Journey's End",
    character: "Frieren",
    manufacturer: "Max Factory",
    category: "FIGMA",
    heightMm: 135,
    releaseYear: 2024,
    releaseMonth: 10,
    msrpJpy: 9800,
    marketUsd: 112,
    drift: 0.15,
    volatility: 0.017,
  },
  {
    name: "Power 1/7 Scale Figure",
    series: "Chainsaw Man",
    character: "Power",
    manufacturer: "Good Smile Company",
    category: "SCALE",
    scale: "1/7",
    heightMm: 230,
    releaseYear: 2024,
    releaseMonth: 1,
    msrpJpy: 23800,
    marketUsd: 232,
    drift: 0.2,
    volatility: 0.024,
  },
  {
    name: "Makima 1/7 Scale Figure",
    series: "Chainsaw Man",
    character: "Makima",
    manufacturer: "Alter",
    category: "SCALE",
    scale: "1/7",
    heightMm: 245,
    releaseYear: 2024,
    releaseMonth: 9,
    msrpJpy: 26800,
    marketUsd: 356,
    drift: 0.42,
    volatility: 0.029,
  },
  {
    name: "Rem 1/7 Wedding Ver.",
    series: "Re:Zero",
    character: "Rem",
    manufacturer: "FREEing",
    category: "SCALE",
    scale: "1/7",
    heightMm: 250,
    releaseYear: 2021,
    releaseMonth: 4,
    msrpJpy: 22800,
    marketUsd: 385,
    drift: 0.31,
    volatility: 0.027,
  },
  {
    name: "Ram 1/7 Wedding Ver.",
    series: "Re:Zero",
    character: "Ram",
    manufacturer: "FREEing",
    category: "SCALE",
    scale: "1/7",
    heightMm: 250,
    releaseYear: 2021,
    releaseMonth: 10,
    msrpJpy: 22800,
    marketUsd: 298,
    drift: 0.24,
    volatility: 0.026,
  },
  {
    name: "Nezuko Kamado 1/8 Scale Figure",
    series: "Demon Slayer",
    character: "Nezuko Kamado",
    manufacturer: "Aniplex",
    category: "SCALE",
    scale: "1/8",
    heightMm: 190,
    releaseYear: 2022,
    releaseMonth: 7,
    msrpJpy: 20900,
    marketUsd: 264,
    drift: 0.16,
    volatility: 0.022,
  },
  {
    name: "Tanjiro Kamado 1/8 Scale Figure",
    series: "Demon Slayer",
    character: "Tanjiro Kamado",
    manufacturer: "Aniplex",
    category: "SCALE",
    scale: "1/8",
    heightMm: 200,
    releaseYear: 2022,
    releaseMonth: 3,
    msrpJpy: 20900,
    marketUsd: 198,
    drift: 0.08,
    volatility: 0.019,
  },
  {
    name: "Hatsune Miku 1/7 Symphony 2024 Ver.",
    series: "Hatsune Miku",
    character: "Hatsune Miku",
    manufacturer: "Good Smile Company",
    category: "SCALE",
    scale: "1/7",
    heightMm: 225,
    releaseYear: 2025,
    releaseMonth: 1,
    msrpJpy: 25800,
    marketUsd: 289,
    drift: 0.22,
    volatility: 0.023,
  },
  {
    name: "Nendoroid Hatsune Miku (Reissue)",
    series: "Hatsune Miku",
    character: "Hatsune Miku",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
    releaseYear: 2023,
    releaseMonth: 9,
    msrpJpy: 5800,
    marketUsd: 64,
    drift: 0.03,
    volatility: 0.011,
  },
  {
    name: "Gojo Satoru 1/7 Scale Figure",
    series: "Jujutsu Kaisen",
    character: "Gojo Satoru",
    manufacturer: "Kotobukiya",
    category: "SCALE",
    scale: "1/7",
    heightMm: 260,
    releaseYear: 2024,
    releaseMonth: 4,
    msrpJpy: 24200,
    marketUsd: 318,
    drift: 0.36,
    volatility: 0.028,
  },
  {
    name: "Nendoroid Gojo Satoru",
    series: "Jujutsu Kaisen",
    character: "Gojo Satoru",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
    releaseYear: 2022,
    releaseMonth: 8,
    msrpJpy: 6500,
    marketUsd: 94,
    drift: 0.14,
    volatility: 0.015,
  },
  {
    name: "Saber/Altria Pendragon 1/7 Alter Ver.",
    series: "Fate/Grand Order",
    character: "Altria Pendragon",
    manufacturer: "Alter",
    category: "SCALE",
    scale: "1/7",
    heightMm: 235,
    releaseYear: 2020,
    releaseMonth: 6,
    msrpJpy: 27800,
    marketUsd: 452,
    drift: 0.29,
    volatility: 0.03,
  },
  {
    name: "Jeanne d'Arc 1/7 Scale Figure",
    series: "Fate/Grand Order",
    character: "Jeanne d'Arc",
    manufacturer: "Ques Q",
    category: "SCALE",
    scale: "1/7",
    heightMm: 240,
    releaseYear: 2021,
    releaseMonth: 11,
    msrpJpy: 25800,
    marketUsd: 276,
    drift: 0.17,
    volatility: 0.025,
  },
  {
    name: "Nendoroid Nezuko Kamado",
    series: "Demon Slayer",
    character: "Nezuko Kamado",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
    releaseYear: 2020,
    releaseMonth: 12,
    msrpJpy: 5900,
    marketUsd: 108,
    drift: 0.19,
    volatility: 0.016,
  },
  {
    name: "Denji 1/7 Scale Figure",
    series: "Chainsaw Man",
    character: "Denji",
    manufacturer: "Max Factory",
    category: "SCALE",
    scale: "1/7",
    heightMm: 215,
    releaseYear: 2025,
    releaseMonth: 6,
    msrpJpy: 23800,
    marketUsd: 214,
    drift: 0.11,
    volatility: 0.02,
  },
  {
    name: "Yor Forger 1/7 Thorn Princess Ver.",
    series: "Spy x Family",
    character: "Yor Forger",
    manufacturer: "Good Smile Company",
    category: "SCALE",
    scale: "1/7",
    heightMm: 255,
    releaseYear: 2025,
    releaseMonth: 9,
    msrpJpy: 26800,
    marketUsd: 302,
    drift: 0.38,
    volatility: 0.027,
  },
  // --- Added from evidence in real listings, then verified against the
  // manufacturers' own product pages. MSRP and release month are present only
  // where a primary source confirmed them. ---
  {
    // Nendoroid #2433. The figure that kept being mistaken for the 1/7 scale.
    name: "Nendoroid Marin Kitagawa: Swimsuit Ver.",
    series: "My Dress-Up Darling",
    character: "Marin Kitagawa",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
  },
  {
    name: "Marin Kitagawa 1/7 Race Queen Ver.",
    series: "My Dress-Up Darling",
    character: "Marin Kitagawa",
    manufacturer: "Aniplex",
    category: "SCALE",
    scale: "1/7",
    heightMm: 230,
    releaseYear: 2026,
    releaseMonth: 3,
    msrpJpy: 22000,
  },
  {
    name: "Racing Miku 2014 Ver. 1/8",
    series: "Hatsune Miku",
    character: "Hatsune Miku",
    manufacturer: "Good Smile Company",
    category: "SCALE",
    scale: "1/8",
    heightMm: 250,
    releaseYear: 2015,
    releaseMonth: 8,
  },
  {
    // Good Smile designate this 1/1 despite its size; using their figure.
    name: "Hatsune Miku Symphony: 5th Anniversary Ver. 1/1",
    series: "Hatsune Miku",
    character: "Hatsune Miku",
    manufacturer: "Good Smile Company",
    category: "SCALE",
    scale: "1/1",
    heightMm: 250,
  },
  {
    // Nendoroid #2100. JAN from the manufacturer listing.
    name: "Nendoroid Hatsune Miku: Beauty Looking Back Ver.",
    series: "Hatsune Miku",
    character: "Hatsune Miku",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
    jan: "4580590174153",
  },
  {
    // Nendoroid #2202.
    name: "Nendoroid Anya Forger: Winter Clothes Ver.",
    series: "Spy x Family",
    character: "Anya Forger",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
  },
  {
    // Nendoroid #2205.
    name: "Nendoroid Satoru Gojo: Tokyo Jujutsu High School Ver.",
    series: "Jujutsu Kaisen",
    character: "Gojo Satoru",
    manufacturer: "Good Smile Company",
    category: "NENDOROID",
    heightMm: 100,
  },
  {
    // Released 2018, reissued 2021 and 2024 at different prices. MSRP omitted
    // because the listings don't say which printing they are.
    name: "Saber/Altria Pendragon (Alter) Casual Ver. 1/7",
    series: "Fate/Grand Order",
    character: "Altria Pendragon",
    manufacturer: "Kotobukiya",
    category: "SCALE",
    scale: "1/7",
  },
  {
    name: "Ruby Hoshino 1/7 Scale Figure",
    series: "Oshi no Ko",
    character: "Ruby Hoshino",
    manufacturer: "Kotobukiya",
    category: "SCALE",
    status: "PREORDER",
    scale: "1/7",
    heightMm: 205,
    releaseYear: 2026,
    releaseMonth: 11,
    msrpJpy: 24800,
    marketUsd: 172,
    drift: 0.06,
    volatility: 0.013,
  },
];

const JPY_TO_USD = 0.0066;
const HISTORY_DAYS = 240;
const CONDITIONS = ["NEW_SEALED", "USED_COMPLETE"] as const;

/** Midnight UTC, `daysAgo` days before today. */
function dayUtc(daysAgo: number): Date {
  const now = new Date();
  const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  d.setUTCDate(d.getUTCDate() - daysAgo);
  return d;
}

/**
 * Synthetic price history is opt-in.
 *
 * It exists so the charts have something to draw during development. It must
 * never reach a public database: fabricated prices presented as a price
 * reference are a lie to anyone reading them, and an instant rejection from any
 * marketplace or retailer reviewing the site.
 */
const DEMO_PRICES = process.argv.includes("--demo-prices");

async function main() {
  if (DEMO_PRICES) {
    console.log("Seeding catalogue WITH SYNTHETIC PRICES (--demo-prices).");
    console.log("Local development only. Never run this against a public database.\n");
  } else {
    console.log("Seeding catalogue only — no prices.");
    console.log("Price history comes from real ingestion and community reports.\n");
  }

  // --- Sources ------------------------------------------------------------
  const sources = [
    { key: "ebay", name: "eBay", homepage: "https://www.ebay.com" },
    { key: "amiami", name: "AmiAmi", homepage: "https://www.amiami.com" },
    { key: "hlj", name: "HobbyLink Japan", homepage: "https://www.hlj.com" },
    { key: "user", name: "Community reported", homepage: null },
  ];
  for (const s of sources) {
    await prisma.source.upsert({
      where: { key: s.key },
      update: { name: s.name, homepage: s.homepage },
      create: s,
    });
  }
  const ebay = await prisma.source.findUniqueOrThrow({ where: { key: "ebay" } });

  // --- Manufacturers & series --------------------------------------------
  const manufacturerIds = new Map<string, string>();
  for (const m of MANUFACTURERS) {
    const row = await prisma.manufacturer.upsert({
      where: { name: m.name },
      update: { websiteUrl: m.websiteUrl },
      create: { name: m.name, slug: slugify(m.name), websiteUrl: m.websiteUrl },
    });
    manufacturerIds.set(m.name, row.id);
  }

  const seriesIds = new Map<string, string>();
  for (const name of SERIES) {
    const row = await prisma.series.upsert({
      where: { name },
      update: {},
      create: { name, slug: slugify(name) },
    });
    seriesIds.set(name, row.id);
  }

  // --- Figures ------------------------------------------------------------
  let figureIndex = 0;
  for (const f of FIGURES) {
    figureIndex += 1;
    const seriesId = seriesIds.get(f.series)!;
    const manufacturerId = manufacturerIds.get(f.manufacturer)!;

    const character = await prisma.character.upsert({
      where: { name_seriesId: { name: f.character, seriesId } },
      update: {},
      create: {
        name: f.character,
        slug: slugify(`${f.character}-${f.series}`),
        seriesId,
      },
    });

    const slug = slugify(`${f.name}-${f.manufacturer}`);
    // Day 15 is a placeholder within a known month; only the month is claimed.
    const releaseDate =
      f.releaseYear && f.releaseMonth
        ? new Date(Date.UTC(f.releaseYear, f.releaseMonth - 1, 15))
        : null;

    const figure = await prisma.figure.upsert({
      where: { slug },
      update: {},
      create: {
        slug,
        name: f.name,
        category: f.category,
        status: f.status ?? "RELEASED",
        scale: f.scale ?? null,
        heightMm: f.heightMm ?? null,
        releaseDate,
        // Both or neither — an amount without its currency is meaningless.
        msrpAmount: f.msrpJpy ?? null,
        msrpCurrency: f.msrpJpy ? "JPY" : null,
        manufacturerId,
        seriesId,
        characters: { connect: { id: character.id } },
        description: `${f.name} by ${f.manufacturer}, from ${f.series}.`,
      },
    });

    // A barcode identifies a product exactly, where a title match only guesses.
    // Worth storing wherever it's known, ready for matching to use.
    if (f.jan) {
      await prisma.figureIdentifier.upsert({
        where: { kind_value: { kind: "JAN", value: f.jan } },
        update: { figureId: figure.id },
        create: { figureId: figure.id, kind: "JAN", value: f.jan },
      });
    }

    // Synthetic history needs parameters that only the original demo entries
    // carry. Figures added from real evidence have none, and must not be given
    // invented ones.
    if (!DEMO_PRICES || f.marketUsd === undefined) {
      console.log(`  ${figure.name}`);
      continue;
    }

    // --- Synthetic price history ----------------------------------------
    // Only with --demo-prices. Walk backwards from today's known market value
    // so the newest point is exactly `marketUsd`, then let drift + noise
    // generate the past.
    const rng = makeRng(0x5eed + figureIndex * 7919);
    const dailyDrift = (f.drift ?? 0) / 365;

    const seriesByDay: number[] = new Array(HISTORY_DAYS);
    let value = f.marketUsd!;
    for (let i = 0; i < HISTORY_DAYS; i++) {
      seriesByDay[HISTORY_DAYS - 1 - i] = value;
      const shock = (rng() - 0.5) * 2 * (f.volatility ?? 0);
      value = value / (1 + dailyDrift + shock);
      value = Math.max(value, (f.msrpJpy ?? 0) * JPY_TO_USD * 0.5);
    }

    const snapshotRows: {
      figureId: string;
      condition: (typeof CONDITIONS)[number];
      date: Date;
      minUsd: number;
      medianUsd: number;
      avgUsd: number;
      maxUsd: number;
      sampleSize: number;
      lowestAskUsd: number;
    }[] = [];
    const saleRows: {
      sourceId: string;
      figureId: string;
      externalId: string;
      condition: (typeof CONDITIONS)[number];
      amount: number;
      currency: string;
      amountUsd: number;
      fxRate: number;
      soldAt: Date;
    }[] = [];

    for (let i = 0; i < HISTORY_DAYS; i++) {
      const daysAgo = HISTORY_DAYS - 1 - i;
      const date = dayUtc(daysAgo);
      const base = seriesByDay[i];

      for (const condition of CONDITIONS) {
        // Used copies trade at a discount to sealed.
        const conditionFactor = condition === "NEW_SEALED" ? 1 : 0.72;
        // Not every figure sells every day; rarer/pricier ones sell less often.
        const dailySales = Math.floor(rng() * (base > 300 ? 2.2 : 4.0));
        if (dailySales === 0) continue;

        const prices: number[] = [];
        for (let k = 0; k < dailySales; k++) {
          const spread = 1 + (rng() - 0.5) * 0.18;
          const price = Math.round(base * conditionFactor * spread * 100) / 100;
          prices.push(price);

          saleRows.push({
            sourceId: ebay.id,
            figureId: figure.id,
            externalId: `seed-${figure.id}-${condition}-${daysAgo}-${k}`,
            condition,
            amount: price,
            currency: "USD",
            amountUsd: price,
            fxRate: 1,
            soldAt: new Date(date.getTime() + 1000 * 60 * 60 * (8 + k)),
          });
        }

        snapshotRows.push({
          figureId: figure.id,
          condition,
          date,
          minUsd: Math.min(...prices),
          medianUsd: Math.round(median(prices) * 100) / 100,
          avgUsd: Math.round((prices.reduce((a, b) => a + b, 0) / prices.length) * 100) / 100,
          maxUsd: Math.max(...prices),
          sampleSize: prices.length,
          // Asking prices sit above realized prices.
          lowestAskUsd: Math.round(Math.min(...prices) * 1.12 * 100) / 100,
        });
      }
    }

    await prisma.priceSnapshot.deleteMany({ where: { figureId: figure.id } });
    await prisma.priceSnapshot.createMany({ data: snapshotRows });
    await prisma.sale.deleteMany({ where: { figureId: figure.id, source: { key: "ebay" } } });
    await prisma.sale.createMany({ data: saleRows, skipDuplicates: true });

    // A handful of live listings, priced a little above market.
    await prisma.listing.deleteMany({ where: { figureId: figure.id } });
    const listingCount = 2 + Math.floor(rng() * 4);
    await prisma.listing.createMany({
      data: Array.from({ length: listingCount }, (_, k) => {
        const markup = 1.05 + rng() * 0.35;
        const price = Math.round(f.marketUsd! * markup * 100) / 100;
        return {
          sourceId: ebay.id,
          figureId: figure.id,
          externalId: `seed-listing-${figure.id}-${k}`,
          title: `${f.name} ${f.manufacturer} ${k % 2 === 0 ? "US Seller" : "From Japan"}`,
          url: "https://www.ebay.com/",
          condition: (k % 3 === 0 ? "USED_COMPLETE" : "NEW_SEALED") as (typeof CONDITIONS)[number],
          amount: price,
          currency: "USD",
          amountUsd: price,
          fxRate: 1,
          shippingUsd: k % 2 === 0 ? 12.5 : 34.0,
          matchScore: 0.95,
        };
      }),
    });

    console.log(`  ${figure.name} — ${snapshotRows.length} snapshots, ${saleRows.length} sales`);
  }

  console.log("Aggregating figure stats…");
  await recomputeFigureStats();

  // Without this a freshly seeded database has an empty search index, and
  // nothing is findable until the nightly job runs.
  const indexed = await rebuildAllSearchText();
  console.log(`Search text built for ${indexed} figures.`);
  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
